run:
  timeout: 120s
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
